### ISSUE TITLE
ImportError: No module named 'dateutil'

### ISSUE THREAD

**Issue by byxor** [414owen/Github-Work-Visualiser#1]
I encountered a missing dependency problem while trying to run github.py.

* I'm on Ubuntu 16.04.
* I installed all the relevant pip dependencies with `sudo python3 -m pip install -r requirements.txt --upgrade`

## Demonstration of problem:

```bash
$ python3 ./github.py 
Traceback (most recent call last):
  File "./github.py", line 4, in <module>
    import dateutil.parser
ImportError: No module named 'dateutil'
```

## Quick fix:

I was able to install this dependency by randomly running a bunch of ambiguous commands:
```
sudo apt-get install python-dateutil
sudo python3 -m pip install dateutil
sudo python3 -m pip install numpy python-dateutil pytz pyparsing six --force-reinstall --upgrade
```

Most of the stuff in there is unnecessary, but hey, it works.

**Comment by 414owen** [comment]
Thanks for bringing this to my attention, byxor, I'll look into the problem and hopefully have a more permanent solution for you within the next thirty seconds.
